apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-meta
spec:
  project: argocd
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-meta
    repoURL: 'https://github.com/reegnz/kube-cd'
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
