apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
spec:
  project: plumbing
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: plumbing/namespaces
    repoURL: 'https://github.com/reegnz/kube-cd'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
